/* import type { Metadata } from "next"; */
import { Rubik } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const rubik = Rubik({
  variable: "--font-rubik",
  display: 'swap',
  subsets: ["latin"],
  weight: ['300', '400', '500', '700']
});
  
/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar/>
      <body
        className={`${rubik.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
