/* import type { Metadata } from "next"; */
import { Rubik } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const rubik = Rubik({
  variable: "--font-rubik",
  display: 'swap',
  subsets: ["latin"],
  weight: ['300', '400', '500', '700']
});
  
/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable}`}>
        <NavBar/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
